2025-03-19 05:40:56,182 - app - INFO - Get posts request from IP: 172.19.0.1
2025-03-19 05:40:56,208 - app - INFO - Successfully retrieved 0 posts from IP: 172.19.0.1
2025-03-19 05:46:52,682 - app - INFO - Login attempt received from IP: 172.19.0.1
2025-03-19 05:46:52,746 - app - INFO - User not found: testuser1 - login attempt from IP: 172.19.0.1
2025-03-19 05:47:13,753 - app - INFO - Registration attempt received from IP: 172.19.0.1
2025-03-19 05:47:13,920 - app - INFO - User testuser1 created successfully from IP: 172.19.0.1
2025-03-19 05:48:02,859 - app - INFO - Login attempt received from IP: 172.19.0.1
2025-03-19 05:48:02,921 - app - INFO - User not found: None - login attempt from IP: 172.19.0.1
2025-03-19 05:48:04,425 - app - INFO - Login attempt received from IP: 172.19.0.1
2025-03-19 05:48:04,719 - app - INFO - Generating token with payload: {'username': 'testuser1', 'exp': datetime.datetime(2025, 3, 19, 6, 48, 4, 718868)}
2025-03-19 05:48:04,723 - app - INFO - User testuser1 logged in successfully from IP: 172.19.0.1
2025-03-19 05:49:51,438 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 05:49:51,441 - app - WARNING - Invalid token for create_post request from IP: 172.19.0.1
2025-03-19 05:50:08,089 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 05:50:08,091 - app - WARNING - Invalid token for create_post request from IP: 172.19.0.1
2025-03-19 05:53:00,961 - app - INFO - Token renewal attempt received from IP: 172.19.0.1
2025-03-19 05:53:00,963 - app - WARNING - Token renewal attempt with invalid token from IP: 172.19.0.1
2025-03-19 06:30:35,963 - app - INFO - Get posts request from IP: 172.19.0.1
2025-03-19 06:30:36,082 - app - INFO - Successfully retrieved 0 posts from IP: 172.19.0.1
2025-03-19 06:35:10,364 - app - INFO - Login attempt received from IP: 172.19.0.1
2025-03-19 06:35:10,569 - app - INFO - Generating token with payload: {'username': 'testuser1', 'exp': datetime.datetime(2025, 3, 19, 7, 35, 10, 569840)}
2025-03-19 06:35:10,575 - app - INFO - User testuser1 logged in successfully from IP: 172.19.0.1
2025-03-19 06:36:57,162 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 06:36:57,192 - app - WARNING - Token missing for create_post request from IP: 172.19.0.1
2025-03-19 06:41:00,123 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 06:41:00,125 - app - WARNING - Token missing for create_post request from IP: 172.19.0.1
2025-03-19 06:41:19,662 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 06:41:19,664 - app - WARNING - Token missing for create_post request from IP: 172.19.0.1
2025-03-19 06:47:48,058 - app - INFO - Most read posts request from IP: 172.19.0.1
2025-03-19 06:47:48,063 - app - INFO - No posts read today - request from IP: 172.19.0.1
2025-03-19 06:56:00,472 - app - INFO - Get posts request from IP: 172.19.0.1
2025-03-19 06:56:00,496 - app - INFO - Successfully retrieved 0 posts from IP: 172.19.0.1
2025-03-19 07:01:42,723 - app - INFO - Top ten user subscriber request received from IP: 172.19.0.1
2025-03-19 07:01:42,749 - app - ERROR - Top ten user subscriber error for IP 172.19.0.1: 'subscribers'
Traceback (most recent call last):
  File "/app/src/routes/analyze.py", line 83, in top_ten_user_subscriber
    "subscribers": len(user["subscribers"])
                       ~~~~^^^^^^^^^^^^^^^
KeyError: 'subscribers'

2025-03-19 07:03:14,104 - app - INFO - Token renewal attempt received from IP: 172.19.0.1
2025-03-19 07:03:14,105 - app - WARNING - Token renewal attempt without token from IP: 172.19.0.1
2025-03-19 07:04:51,185 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 07:04:51,187 - app - WARNING - Token missing for create_post request from IP: 172.19.0.1
2025-03-19 07:08:50,141 - app - INFO - Get posts request from IP: 172.19.0.1
2025-03-19 07:08:50,165 - app - INFO - Successfully retrieved 0 posts from IP: 172.19.0.1
2025-03-19 07:09:14,955 - app - INFO - Create post request from IP: 172.19.0.1
2025-03-19 07:09:14,958 - app - WARNING - Token missing for create_post request from IP: 172.19.0.1
2025-03-19 07:17:45,975 - app - INFO - Flask app started
2025-03-19 07:17:47,647 - app - INFO - Flask app started
2025-03-19 07:19:40,515 - app - INFO - Login attempt received from IP: 172.19.0.1
2025-03-19 07:19:40,725 - app - WARNING - Invalid password for user: testuser1 from IP: 172.19.0.1
2025-03-19 07:20:52,147 - app - INFO - Check user info request received from IP: 172.19.0.1
2025-03-19 07:20:52,382 - app - ERROR - Check user info error for IP 172.19.0.1: Object of type ObjectId is not JSON serializable
Traceback (most recent call last):
  File "/app/src/routes/user.py", line 175, in check_user_info
    return jsonify(user_info), 200
           ~~~~~~~^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flask/json/__init__.py", line 170, in jsonify
    return current_app.json.response(*args, **kwargs)  # type: ignore[return-value]
           ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flask/json/provider.py", line 214, in response
    f"{self.dumps(obj, **dump_args)}\n", mimetype=self.mimetype
       ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/flask/json/provider.py", line 179, in dumps
    return json.dumps(obj, **kwargs)
           ~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
          ~~~~~~^^^^^
  File "/usr/local/lib/python3.13/json/encoder.py", line 200, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.13/json/encoder.py", line 261, in iterencode
    return _iterencode(o, 0)
  File "/usr/local/lib/python3.13/site-packages/flask/json/provider.py", line 121, in _default
    raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
TypeError: Object of type ObjectId is not JSON serializable

